# Generated by Django 2.1.12 on 2019-09-23 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tube.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='TubeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_channel', models.BooleanField(default=False)),
                ('image', models.ImageField(default='users_profile/default.jpg', upload_to='users_profile')),
                ('channel', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tube.TubeChannel')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscribed_channels', to='tube.TubeChannel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('thumbnail', models.ImageField(upload_to='profile_pics')),
                ('views', models.IntegerField(default=0)),
                ('video_content', models.FileField(upload_to=tube.models.directory_path)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.TubeChannel')),
                ('tags', models.ManyToManyField(blank=True, to='tube.Tag')),
            ],
        ),
    ]
