# Generated by Django 2.1.5 on 2019-09-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails'),
        ),
    ]
