# Generated by Django 2.1.12 on 2019-10-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_auto_20190925_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tubeuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribed_tubeusers', to='tube.TubeChannel'),
        ),
    ]
